---
title: "Siegle-Hw3"
author: "Aaron_Siegle"
date: "2026-09-27"
output: html_document
---

```{r, message=FALSE}
# load libraries
library(spdep)
library(sf)
library(terra)
library(spatialreg)
library(viridis)
library(data.table)
library(spectralGP)
library(RColorBrewer)
```


```{r}
# Import the data
pres_data_path <- "C:/Users/aasie/OneDrive/Documentos/GIS713-Homework3/Data/2016_US_County_Level_Presidential_Results.csv"
acs_county_data_path <- "C:/Users/aasie/OneDrive/Documentos/GIS713-Homework3/Data/acs2015_county_data.csv"
us_county_shp_path <- "C:/Users/aasie/OneDrive/Documentos/GIS713-Homework3/cb_2015_us_county_20m/cb_2015_us_county_20m.shp"
us_county <- st_read(us_county_shp_path)
election_results <- fread(pres_data_path)
acs_counties <- fread(acs_county_data_path)
head(election_results)
head(acs_counties)
head(us_county)
```
```{r}
# Look at column names in the datasets 
colnames(acs_counties)
colnames(election_results)
print(nrow(acs_counties))
print(nrow(election_results))
```

```{r}
# Remove non-CONUS counties from both datasets 
acs_counties <- acs_counties[
  !acs_counties$State %in% c("Alaska", "Hawaii", "Puerto Rico"), ]
election_results <- election_results[!state_abbr == "AK" & 
                                    !state_abbr == "HI" & 
                                    !state_abbr == "PR"]
print(nrow(acs_counties_spatial))
print(nrow(election_results))
```


```{r}
# Spatial join between the two datasets
election_counties <- merge(acs_counties,
                           election_results,
                           by.x="CensusId", 
                           by.y="combined_fips", 
                           all.x=TRUE, 
                           all.y=TRUE
                           )
head(election_counties)
colnames(election_counties)
```

```{r}
# Create new variables 
election_counties[, frac_non_citizen := 1 - (Citizen / TotalPop)][,
                  frac_women := Women/TotalPop][,
                  frac_nonwhite := 1 - (White/TotalPop)][,
                  frac_voting := total_votes/TotalPop]
head(election_counties)
```

```{r}
# Subset only to specified variables
election_counties_subset <- election_counties[, .SD, .SDcols = c(
    "CensusId", "State", "County", 
    "per_dem", "per_gop", "frac_voting", 
    "frac_women", "frac_nonwhite", "frac_non_citizen", 
    "Income", "Poverty", "ChildPoverty", "Professional"
    )]
colnames(election_counties_subset)
```

```{r}
# Subset only to counties where all variables are complete 
election_counties_complete <- election_counties_subset[
  complete.cases(election_counties_subset)
]
print(nrow(election_counties_subset))
print(nrow(election_counties_complete))
```

```{r}
# Question 2: Create a map with an appropriate divergent color ramp that shows the GOP vote fraction for each county
# Join in the spatial attributes from the shapefile
us_county$FIPS <- as.numeric(paste0(us_county$STATEFP, us_county$COUNTYFP))
us_county$FIPS <- as.integer(us_county$FIPS)
election_counties_complete <- as.data.frame(election_counties_complete)
acs_counties_spatial <- merge(
  us_county, 
  election_counties_complete,
  by.x = "FIPS", 
  by.y = "CensusId",
  all.x = TRUE,
  all.y = TRUE
)
head(acs_counties_spatial)
```

```{r}
plot(acs_counties_spatial["per_gop"], 
     breaks = seq(0,1, length.out=11),
     pal = rev(brewer.pal(10, "RdBu")), 
     main = "GOP Vote Fraction by County", 
     xlim = c(-125, -66), ylim = c(24, 50),
     border = NA
     )
```

```{r}
# Question 3: Explain the variation in county-level GOP vote share using the covariates. Test for spatial dependence and fit a spatial regression variant if necessary (use lm.morantest rather than moran.test).
# Build nearest neighbors 
nb <- poly2nb()
```



